   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buyer-service-k8s
spec: 
  selector:
    matchLabels: 
      app: buyer-service-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: buyer-service-k8s
    spec: 
      containers:
        - name: buyer-service-k8s
          image: 2022reg04ctse/buyer-service-k8s:latest
          ports: 
            - containerPort: 5005 