apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-k8s
spec: 
  selector:
    matchLabels: 
      app: order-service-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: order-service-k8s
    spec: 
      containers:
        - name: order-service-k8s
          image: 2022reg04ctse/order-service-k8s:v1
          ports: 
            - containerPort: 5003 
