name: Order service CICD Pipeline

on:
  push:
    branches:
      - main

jobs:

  ##build and deploy image to docker hub

  build:
    name: Build and containerlize order service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node for order service
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: './OrderService/package-lock.json'

      - name: Install dependencies for Order Service
        run: npm ci
        working-directory: OrderService

      - name: Login to docker hub 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Build image and push
        uses: docker/build-push-action@v2
        with:
          context: ./OrderService
          file: ./OrderService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/orderservice:v1
