
name: CI/CD Pipeline for backend services

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: us-central1  

jobs:
  build:
    name: Build and containerize all services 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies for MessagingService
        run: npm ci
        working-directory: MessagingService
        
      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ secrets.DOCKER_USERNAME_CH }}/messaging-service-k8s
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME_CH }}
          password: ${{ secrets.DOCKER_PASSWORD_CH }}

    ## Repeat steps Install dependencies and build docker image for other services

  deploy: 
    name: Deploy services to k8s cluster
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploying MessagingService
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
          CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
          ZONE_NAME: us-central1-c
        with:
          args: apply -f MessagingService/kubernetes

