name: CI/CD Pipeline for backend services

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: us-central1  

jobs:
  build:
    name: Build and containerize all services 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3    
 
      - name: Setup Node for Messaging Service
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'npm'
          cache-dependency-path: './MessagingService/package-lock.json'
     
      - name: Setup Node for Buyer Service
        uses: actions/setup-node@v3
        with:
          node-version: '14.17.0'
          cache: 'npm'
          cache-dependency-path: './BuyerService/package-lock.json'

      - name: Setup node for order service
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: './OrderService/package-lock.json'

      - name: Setup node for Seller service
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: './SellerService/package-lock.json'
        
      - name: Install dependencies for MessagingService
        run: npm ci
        working-directory: MessagingService
        
      - name: Install dependencies for BuyerService
        run: npm ci
        working-directory: BuyerService

      - name: Install dependencies for Order Service
        run: npm ci
        working-directory: OrderService   

      - name: Install dependencies for Seller Service
        run: npm ci
        working-directory: SellerService     


      - name: Build and push Docker image for MessagingService
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          dockerfile: './MessagingService/Dockerfile'
          directory: './MessagingService'
          image: ${{ secrets.DOCKER_USERNAME_CH }}/messaging-service-k8s
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME_CH }}
          password: ${{ secrets.DOCKER_PASSWORD_CH }}
      
      - name: Build and push Docker image of Buyerservice
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          dockerfile: './BuyerService/Dockerfile'
          directory: './BuyerService'
          image: ${{ secrets.DOCKER_USERNAME_CH }}/buyer-service-k8s
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME_CH }}
          password: ${{ secrets.DOCKER_PASSWORD_CH }}

      - name: Build and push Docker image for OrderService
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          dockerfile: './OrderService/Dockerfile'
          directory: './OrderService'
          image: ${{ secrets.DOCKER_USERNAME_CH }}/order-service-k8s
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME_CH }}
          password: ${{ secrets.DOCKER_PASSWORD_CH }}
          
      - name: Build and push Docker image for SellerService
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          dockerfile: './SellerService/Dockerfile'
          directory: './SellerService'
          image: ${{ secrets.DOCKER_USERNAME_CH }}/seller-service-k8s
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME_CH }}
          password: ${{ secrets.DOCKER_PASSWORD_CH }}

          
  deploy: 
    name: Deploy services to k8s cluster
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploying MessagingService
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
          CLUSTER_NAME: ${{ env.GKE_CLUSTER }}
          ZONE_NAME: ${{ env.GKE_ZONE }}
        with:
          args: apply -f MessagingService/kubernetes
          
      - name: Deploying BuyerService
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
          CLUSTER_NAME: ${{ env.GKE_CLUSTER }}
          ZONE_NAME: ${{ env.GKE_ZONE }}
        with:
          args: apply -f BuyerService/kubernetes

      - name: Deploying OrderService
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
          CLUSTER_NAME: ${{ env.GKE_CLUSTER }}
          ZONE_NAME: ${{ env.GKE_ZONE }}
        with:
          args: apply -f OrderService/kubernetes

      - name: Deploying SellerService
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
          CLUSTER_NAME: ${{ env.GKE_CLUSTER }}
          ZONE_NAME: ${{ env.GKE_ZONE }}
        with:
          args: apply -f SellerService/k8s

